import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { Header } from "~/components/header";
import { api, type RouterOutputs } from "../utils/api";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Simple Notes App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
      </main>
    </>
  );
};

export default Home;

const Content: React.FC = () => {
  const { data: sessionData } = useSession();
  
  const { data: topics, refetch: refetchTopics } = api.topic.getAll.useQuery(
    undefined, // no input
    {
      enabled: sessionData?.user !== undefined,
      }
  );

  return (
    <div>
      {JSON.stringify(topics)}
    </div>
  );
};